name: update
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # run every hour
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: scrape
        working-directory: scraper
        run: |
          npm ci
          npm start
      - uses: actions/upload-artifact@v3
        with:
          name: css
          path: css

  dump:
    runs-on: ubuntu-latest
    needs: scrape
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v2
        with:
          name: css
          path: css
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: dump
        working-directory: dumper
        run: |
          ls -al ../css
          npm start
      - uses: actions/upload-artifact@v3
        with:
          name: dump
          path: dump

  commit:
    runs-on: ubuntu-latest
    needs: dump
    steps:
      - uses: actions/download-artifact@v2
        with:
            name: dump
            path: dump
      - uses: actions/checkout@v4
      - name: commit dump
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "routine dump"
          git push

  publish:
    runs-on: ubuntu-latest
    needs: commit
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dump
          path: dump
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}